### ISSUE TITLE
Argh what am i doing wrong?

### ISSUE THREAD

**Issue by alexsambacanada** [jprichardson/node-suppose#44]
Sorry, this is likely a dumb question but all I'm trying to do here is simply telnet into a device.  My console.log at the end is continually returning undefined and the debug.txt never has anything in it.  I've also noticed that when i use .on instead of .when (for the expect statements) i actually get some kind of output although it's an error.  Using .when gives me nothing.  Im using suppose version 0.6.2.  Any idea where I'm being dumb here?

```
const suppose = require('suppose');
const fs = require('fs')

suppose('telnet' ['10.0.0.91'],{ debug: fs.createWriteStream('/tmp/debug.txt') })
.when('login:').respond('admin\n')
.when('Password:').respond('password')
 .on('error', function(err){
    console.log(err.message);
 })
    .end(function(code) {
        console.log(code);
    });

```

**Comment by piranna** [comment]
Maybe in fact you are getting an error? What error do you get?

**Comment by alexsambacanada** [comment]
So here's my code revised:

```
suppose('telnet' ['10.0.0.91'],{ debug: fs.createWriteStream('/tmp/debug.txt') })
.on('login:').respond('admin\n')
.on('Password:').respond('password')
.end(function(code) {
        console.log(code);
    });
```

This results with:

> events.js:238
>     throw new TypeError('"listener" argument must be a function');
>     ^
> 
> TypeError: "listener" argument must be a function
>     at _addListener (events.js:238:11)
>     at SupposeStream.addListener (events.js:298:10)
>     at SupposeStream.Readable.on (_stream_readable.js:761:35)
>     at Object.<anonymous> (/Users/awitte/Documents/GitHub/switch_backup_node/westell.js:5:2)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)
>     at Function.Module.runMain (module.js:605:10)

If I change the .on to .when like this:

```
const suppose = require('suppose');
const fs = require('fs')


suppose('telnet' ['10.0.0.91'],{ debug: fs.createWriteStream('/tmp/debug.txt') })
.when('login:').respond('admin\n')
.when('Password:').respond('password')
.end(function(code) {
        console.log(code);
    });
```

Gives me this:

> undefined

I'm likely just doing something dumb....  any thoughts?
